---
mqtt:
  connection:
    host: broker.lan
    port: 1883
    id: some-id
  credentials:
    user: user
    password: password
i2c:
  device: /dev/i2c-1
ios:
  inputs:
  - address: 0x20  # has 8 digital inputs (implicitly)
    chip: PCF8574
    pins:
    - bedroom
    - living_room
  - address: 0x38
    chip: PCF8574
    pins:
    - button_one_up
    - button_one_down
  outputs:
  - address: 0x39  # has 8 digital outputs (implicitly)
    chip: MAX7311
    pins: []
  - address: 0x3a
    chip: PCF8574
    pins:
    - blind_one_up
    - blind_one_down
